### ISSUE TITLE
Implement bench

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#16]
Goal is that with a given set of network weights, we should explore the exact same tree with one thread.  This should allow us to refactor the search/eval code without fear.  Same concept exists in SF and is extremely useful.

We would specify a default set of weights, either random or perhaps the supervised network, and then a series of PGNs that the evaluation should stay consistent for.

**Comment by gcp** [comment]
This may be very tricky because you are dependent on floating point math and rounding. See: https://github.com/gcp/leela-zero/issues/300

**Comment by Akababa** [comment]
Is it possible to run bench on CPU or VM to ensure consistent results?

**Comment by gcp** [comment]
For CPU only use it should be OK as long as you fix the compiler and compiler version.

**Comment by vondele** [comment]
@gcp even that doesn't work. Libraries or compiler generated code for a matrix multiply will return slightly different results depending on the alignment of data, as compilers/libraries might have different code paths (e.g. using sse or avx (FMA) or not) depending on alignment relatively to the vector length. Since linux malloc only guarantees 16byte alignment one either has to be extremely careful with all allocates (aligning by hand to 32 or even 64bytes depending on the architecture) or give up on bitwise reproducibility.

I filed an issue with gcc a few years ago (but it is not really a gcc bug), when we ran into this:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64247#c4

**Comment by Akababa** [comment]
Surely distributing a reference software VM image will work for testing purposes, right?

**Comment by gcp** [comment]
I think @vondele just explained that unfortunately no, that won't necessarily work. (But it seems it may be possible to get it to work, with careful use of alignas() etc.)

**Comment by glinscott** [comment]
It's not perfect, but this allowed me to validate the winograd code: https://github.com/glinscott/leela-chess/commit/d607fc33d26cecf40c77b90e706ed5da7f43e306

**Comment by glinscott** [comment]
Current bench is good enough :).
