### ISSUE TITLE
LCZero thinks long even when only one move is possible

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#183]
It seems that LCZero does full MCTS even when only one move is possible.

That doesn't seem useful either while training (only the number of playouts in root node is used to train the policy network, right?), nor during the actual play (no need to think if only one move is possible).

**Comment by alreadydone** [comment]
Hmm .. interesting. In Go there are always so many empty points on the board, but in chess this is a real possibility, but should be rare (mostly for the side in check?). There was a discussion in Leela Zero whether to train the policy probability of illegal moves towards zero, because an illegal move can become a very good one if it captures the opponent's stones, and because the neural net (probably due to limited capacity) cannot easily determine legality (depending on liberty counts which can involve many stones). For chess this should be less a problem; I think the current network size is already enough to easily identify illegal moves.

**Comment by killerducky** [comment]
LZGo has a solution for this already (--timemanage on). I will port it later if someone else doesn't do it first.

**Comment by alreadydone** [comment]
Time management should be off for training games, and indeed you need to run the tree search if there are at least two moves since you don't know how the playouts will split among them, but if there's only one legal move you can just set its search probability to one.

**Comment by alreadydone** [comment]
OK I now think this will be a non-issue after tree reuse is merged. The tree search will then not be wasted, and if you don't do it on the forced move you do it later. If you switch to visits, the move after a forced move will be played immediately, since the tree search will add only one node to the tree.

**Comment by mooskagh** [comment]
That's true during the training, but during the ordinary game it will still be an issue.

I noticed that on one of the 40/40 streams yesterday. There were many forced moves (king under check, only one square to escape) and still LCZero thought for a whole minute for every of those moves.

**Comment by alreadydone** [comment]
In ordinary games it should be solved by time management; it plays the move with the highest visit count once the second highest is unlikely to catch up in the remaining playouts / the remaining time.

**Comment by Dorus** [comment]
The combination of tree reuse and time management should solve the majority of the problem. However during tournament games it should probably just play the forced move automatically (unless there is a fixed time per move). The reason is that if there is a fixed time per move, it would be an advantage to expand the tree ahead of time. However if there is a total time, you rather spend that time once you know what your opponent is going to answer after a forced move.

Time-management will only cut thinking time in half and tree reused will still lose the moves it explored on the opponent who did not make a forced move.

**Comment by killerducky** [comment]
No the current LZGo timemanage code moves instantly if there is only 1 legal move. Because there is no 2nd move to overtake the first. Unless there is a bug because that basically never happens in Go.  :)

**Comment by Dorus** [comment]
My mistake, i was too lazy so i didn't check the code. However, even if LZGo doesn't do that, LCZ most definitely does need to do that :)
