### ISSUE TITLE
Duplicate match games

### ISSUE THREAD

**Issue by luigio** [glinscott/leela-chess#205]
These two match games are identical:

http://lczero.org/match_game/18114
http://lczero.org/match_game/18130

Could this be a problem? Should duplicate games count only once towards the final score? Is randomness too low?

**Comment by jkiliani** [comment]
Good catch, I wondered when this would happen the first time. This has been coming for a while, and I think the reason is that policy priors are getting more and more "set in their ways", which makes it harder for Dirichlet noise to perturb them enough that the PV changes.

In my opinion, we need to rethink how we hold matches. Using temperature for the first couple of moves may work, since that forces diversity in the opening more than Dirichlet noise.

**Comment by luigio** [comment]
Just for the record, almost all games in that match start 1. e4 e5 2. Nf3 d6 3. d4 exd4 4. Nxd4 Nf6 5. Nc3 c6 6. Be2 Be7 7. O-O O-O 8. Nf5 Bxf5 9. exf5 d5 10. g4. Philidor is all the rage now.

**Comment by jkiliani** [comment]
I know, and Philidorism has been going on for a while now.

I'm going to make a few tries matching different networks against each other with proportional move selection (t=1) instead of noise. Obviously they will be full of blunders, but it would fix the lack of variety problem we're currently having in match games.

A better solution in my opinion would be some sort of temperature decay schedule, which would force variety in the opening, while quickly reducing that randomness later in the opening and toward the mid- and endgame.

**Comment by evalon32** [comment]
Maybe we should have trained the network to play Chess960 instead: 960 guaranteed unique games to start with :) And since it's a strict superset, it could still play standard chess.

**Comment by luigio** [comment]
And here is quite an unsettling match game:

http://lczero.org/match_game/19738

What on Earth happened there? I don't think LCZero at its current strength can play that badly.

**Comment by jhellis3** [comment]
For the match games, why not just use a shallow opening book?  The games are not used for learning anyway right?

**Comment by luigio** [comment]
I actually like seeing how its opening preferences (or fixations) evolve with time. One duplicate game out of 400 is not a big deal and could be simply left out of the score.

**Comment by evalon32** [comment]
@luigio That match game looks a lot like those played by yesterday's failed nets. Is it possible that some clients are still running code before the move count change, and that throws everything off?

**Comment by jjoshua2** [comment]
if you look at lczero.org there are many still running v3 so yeah.

**Comment by jjoshua2** [comment]
do we have issues with duplicates in training games? I think if we used a 2 ply opening book with all possible legal moves we would enforce much more variety, which should help it learn to play chess in more unusual positions which should make it get stronger faster. Fishtest even uses a 4 ply opening book for this purpose.
It would also have the advantage of saving a lot of time since the first moves are duplicated work by many systems. Those moves only need to be generated once for each net not 100k times a day.

**Comment by ThorAvaTahr** [comment]
Adding human knowledge should be avoided from the viewpoint of performing a clean experiment. Even if just used in matching it has some effect on the process as there is still a gating involved. So opening book is a nogo imho.

**Comment by jjoshua2** [comment]
I agree using a human generated opening book. But using a rules generated opening book of all possible white and black moves of a small depth is no different than using a leela zero with a high temperature and dirichlet noise setting, just a lot faster and cleaner.

**Comment by Dorus** [comment]
And once again always promote is just so much more elegant. Doing proper matches just seem so difficult for chess. :-)

**Comment by jjoshua2** [comment]
It's pretty a solved problem at this point...
