### ISSUE TITLE
Network candidate is tested against not the current best network

### ISSUE THREAD

**Issue by zz4032** [glinscott/leela-chess#213]
As one can see on the matches page, network ID58 played vs. network ID57 while it should have been ID58 vs. ID56. ID56 is the current strongest network considering the previous match results.

**Comment by Dorus** [comment]
Matches are currently used as a safe guard against training bugs (imho the -50 elo threshold is still too high, should be -100 or -200), however by using -50 and matching the network against the current used network, it would still be allowed to crawl out of a local optimum by losing elo multiple networks in a row till it can climb up future again.

Now if you match against current best each time, the -50 elo threshold would be too high for sure.

**Comment by zz4032** [comment]
Ok, that makes sense. The disadvantage is that there is no control about how deep the fall from the previously best network might become. I guess we will see how the current strategy turns out, I hope it does well.

**Comment by zz4032** [comment]
Now we had the chance to observe the development for some time. There has been a decline starting from network 69 and 7 more networks came in after that. None of them came close to the performance of network 69 again until today.
```
Id | Network  | Elo     | Elo Diff to 69

76 | 06f4a98e | 4323.62 | -108.2
75 | a773b283 | 4360.11 | -71.7
74 | 2908f274 | 4388.26 | -43.6
73 | 7f689182 | 4341.03 | -90.8
72 | 2005fe39 | 4368.6  | -63.3
71 | 94fa288f | 4357.52 | -74.3
70 | 0da66312 | 4414.23 | -17.6
69 | 0e7535a7 | 4431.85
```

Whether it's because the network is bounded by the architecture or for other reasons, it seems it does not necessarily regain the strength it had when it started declining and there is a danger of falling even further.
I would opt for testing against best network available (69 in this case) and lowering the threshold to -100 Elo. -50Elo to latest promoted network can be kept as a second condition (just by comparing ratings and without matching it against it).

**Comment by pw31** [comment]
The trouble continues:
![image](https://user-images.githubusercontent.com/18750275/38190295-83323ad0-365b-11e8-8758-14c71775e597.png)
From the last 9 matches, only 2 have been successful, one network was correctly identified as being inferior.  But in 6 out of 9 cases, weaker candidate networks were promoted.  Is this because an early decision was made while many matches were still in progress?  I think the matches are so fast that it wouldn't hurt to wait a bit longer to get more complete results in before making that decision.

**Comment by gsobala** [comment]
The training system is set up to always promote unless the new network is disastrous. 

Howver it is true to say that the performance over the last day or two suggests a genuine stall and it may be time to enlarge the NN.

**Comment by Dorus** [comment]
@pw31 How do you mean? All these matches are within the -50 elo threshold.

Stagnation in machine learning like this is usually an indication of either 1) a bug, 2) too high learning rate or 3) network is near capacity. The 4th option is just bad luck.

Currently i have the feeling we're just having bad luck, also nobody has tested 69 vs 74 yet (as far as i saw), so it's hard to say if 74 really is a decline, self play elo is inflated especially because every network is only tested against the previous one, so it's very possible the elo difference is smaller than the cumulative elo would suggest.

Beside that, always promote has already proven it can work, so the current stagnation is more likely to 1, 2 or 3. Increasing network capacity would be my first pick here, as the current network is rather small and already reached a rather nice elo. (over 2000 by my estimate).

**Comment by MathAndreas** [comment]
No, most candidate networks were promoted because of the new "promote always" policy. Only if ELO difference is more than -50 it is not promoted.

**Comment by pw31** [comment]
OK, if always promoting down to -50 ELO is the policy, than there is no issue.   I have just observed that some match results come in very late, long after the decision about promotion is taken.  This could introduce some problems when for example one network is very weak with long endgames. I have also confused this with Leela Zero (go) where there is a 55% win percentage rule for promotion.

**Comment by Dorus** [comment]
Btw we just had a strong promotion so it's no longer stagnating. That said progress is still slowing down so it would still be interesting to also test larger networks and see if they can already give a good improvement.

**Comment by pw31** [comment]
Good to see two proper promotions since then already, so yes, maybe it all was just back luck probably.  I can strongly recommend zz4032's spreadsheet page 
https://docs.google.com/spreadsheets/d/18UWR4FVhPi0vNwwPreu_avd9ycujGQ5ayR2LzJOWP4s/edit#gid=0 where many versions of LCzero are tested systematically against Stockfish playing at different skill levels.  Accoring to these results, the current best network still is Id63 with close to 2000 ELO, and there was indeed a decreasae Id67 -> Id73 of about 40 ELO.  However, remember the errorbars which are about +/- 100 ELO.

**Comment by Dorus** [comment]
But they tested 73 and not the stronger 74 (guess 74 wasn't out yet when they started the test?) Hope they test 77 and/or 78 next, those should be over 2000 elo for sure.

**Comment by pw31** [comment]
Over night, Id79 was evaluated ELO 2139!  I uploaded a few example games here https://lichess.org/study/0ediX6tY  --  can you smell the breath of alpha zero?

**Comment by zz4032** [comment]
There has been a big improvement since Id 76 indeed.
But I guess we'll never know how it would have turned out with a different promoting limit unless we revert to id 69 and replay the games...
```
Id | Network  | Elo     | Elo Diff to 69
81 | eaafcc53 | 4497.8  | +65.9
80 | 52a9b7a0 | 4505.81 | +74.0
79 | 0978e760 | 4478.08 | +46.2
78 | 8af5b776 | 4474.75 | +42.9
77 | ec518f55 | 4419.34 | -12.5
76 | 06f4a98e | 4323.62 | -108.2
75 | a773b283 | 4360.11 | -71.7
74 | 2908f274 | 4388.26 | -43.6
73 | 7f689182 | 4341.03 | -90.8
72 | 2005fe39 | 4368.6  | -63.3
71 | 94fa288f | 4357.52 | -74.3
70 | 0da66312 | 4414.23 | -17.6
69 | 0e7535a7 | 4431.85
```

**Comment by killerducky** [comment]
This is mostly moot now that we gate at -150 Elo.
