### ISSUE TITLE
leela-chess or leela-zero-chess

### ISSUE THREAD

**Issue by brianprichardson** [glinscott/leela-chess#24]
Perhaps somewhat pedantic, but if the goal here is minimal chess-specific info, then shouldn't the term "zero" be in the name.  Leela by itself is quite go-centric, whereas leela-zero is the minimalist alpha-go-zero approach, I think.

**Comment by gcp** [comment]
Well, for Go Leela with hand coded Go knowledge already existed, so I had to differentiate the AZ style program from the regular one. I don't think you have that problem in chess. 

>Leela by itself is quite go-centric

I think that's actually cute because using MCTS and DCNN, although very common in Go, is certainly "new" to the chess world. When Leela started out (think 2007), it was a Go program written like a chessprogrammer would write one, i.e. a fast, deep tree searcher with a "small" eval instead of huge pattern databases. We've now come full circle.

**Comment by glinscott** [comment]
I've called the executable "lczero", short for "leela-chess-zero".  I'm open to any name really :).

Also, I'm not really sure the goal is minimal chess info.  I agree, that's probably the most interesting area to pursue.  But "cheating" by adding attack information or something as an input plane is quite interesting.

Anyhow, that can be for later, after we get a strong engine trained up that approximates the AlphaZero paper (although the training methods will probably have to be a bit different given their absurd amount of compute).

**Comment by glinscott** [comment]
lczero.org it is :).
