### ISSUE TITLE
Have separate probabilities for win/draw/lose

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#241]
That's a pretty speculative idea, but it's very straightforward to implement and it gives more control on playing style which may be useful for later experiments.

So, the idea is instead of having one value out of value head (from -1 to 1), to have three values (passed through softmax layer):

- Win probability
- Lose probability
- Draw probability

During the MCTS, this will be translated into one value:
If we scale Q from 0 to 1:
```
win + 0.5 draw  <- exactly what we have now
win + draw  <- the program tries not to lose, winning is not important
win  <-  the program wants to win and plays aggressively, draw is not acceptable.
```
Also other levels of coefficients between draw and lose are possible to tweak aggresiveness more gradually (in this example it's 0.5\*draw, 1\*draw and 0\*draw).

The same if we scale Q from -1 to 1:
```
win - lose  <- that's what we have now
win + draw - lose  <- win or draw is fine
win - draw - lose  <-  the program wants to win and plays aggressively, draw is not acceptable.
```
(again it allows more gradual tweaks of draw from -1 to 1)

**Comment by jkiliani** [comment]
Sounds like a great idea! Giving two out of the three values would suffice though, since all three are necessarily dependent. A "contemptuous network" would have to be retrained from scratch, but at higher playing levels this may well be what many users are going to be looking for...

**Comment by Akababa** [comment]
Could a similar contempt effect be achieved by scaling the value output to [0,1] and then squaring? Then a win is still worth 1 point and loss is still 0, but draw is 0.25 (translated back would be 1,-1,-0.5)

**Comment by lightvector** [comment]
This has the nice advantage of making the value head much more flexible for later choice of style. 
@jkiliani - It's possibly simpler to just give all 3 values, the same way that for the policy head you don't pick and remove one of the outputs and removing it because it can be inferred from the others? If you just have 3 outputs in the value head and softmax them, the softmax itself cleanly enforces that their sum is 1, no?

Unfortunately this doesn't affect the policy head. If you want to make the policy head also responsive to different objectives, it's more complicated, but in principle still you can do it by providing the coefficient on the utility of a draw as an input and then varying that value during training games.

**Comment by mooskagh** [comment]
We can still train policy head as win + 0.5 lose, and only bias it during MCTS. What you suggested is a good idea indeed, but it requires too many changes and diverts the progress too much.

I guess it still will affect style while not weaken the engine.

Actually, we can train both "old style" win probability {-1..1}, and individual probabilities {win, lose, draw}. That way we are still fully compliant with AZ spec while having individual probabilities in hand,

**Comment by evalon32** [comment]
This has value aside from playing style: Leela would be able to offer a draw, similar to resignation.

**Comment by mooskagh** [comment]
This issue was moved to LeelaChessZero/lc0#79
