### ISSUE TITLE
Still not working on fritz 14

### ISSUE THREAD

**Issue by maximiliano1956** [glinscott/leela-chess#315]
I follow the wiki instructions to install leela on a Fritz GUI.
The engine name is shown when i select InBetween,exe as the engine
but when i press the okay button nothing happens.

**Comment by Akababa** [comment]
Did you follow these instructions? https://github.com/glinscott/leela-chess/wiki/Running-LCZero-in-a-Chess-GUI

**Comment by zz4032** [comment]
The official release version didn't work for me too. Need to take a binary from current master (appveyor or what it's called)...

**Comment by Ipmanchess** [comment]
And that still doesn't work for me!
You have to edit Inbetween.ini with no clear parameters that it makes confusing..spaces no spaces ,add -uci or --uci ..something more or less..not clear for most people!
Why not make one zip file with all needed files and ini file ,parameters included.
So that we can put it in one folder..open FritzGui and install engine like we get use too.
Or use clear screens with everything on it..but then people still not sure they have the right files..

**Comment by Ipmanchess** [comment]
I got it working !! -> **CommandLine := lczero.exe --uci**
Just like that..leave out -w weights.txt and use --uci
In FritzGui LCZero shows only 1 CPU even i put it on -t 18 ,but it looks like it use 18cores

**Comment by maximiliano1956** [comment]
Update:
Using v0.6 it works!
