### ISSUE TITLE
Incorrect sampling from ChunkFiles

### ISSUE THREAD

**Issue by Error323** [glinscott/leela-chess#33]
https://github.com/glinscott/leela-chess/blob/d607fc33d26cecf40c77b90e706ed5da7f43e306/training/tf/leela_to_proto.py#L61-L74

Currently consecutive positions from a game are gathered in a dataset via the next iterators. Instead, random sampling should be performed.

**Comment by Error323** [comment]
@glinscott I'm thinking about the approach on howto do this, but I'm not sure yet. What about skipping every 70*num_workers positions?

**Comment by Akababa** [comment]
Wouldn't random sampling result in training games in your test data?

**Comment by Error323** [comment]
I'm first shuffling the chunks and separating them for train and test.

**Comment by gcp** [comment]
I would recommend to do the training/validation split at the PGN parsing level (by switching from outputting to /training to /test after a certain amount of games have been processed), and then make almost everything but parse.py/tfprocess.py unaware of the difference.

This avoids a lot of complexity, IMHO. It's hard to reason about the existing code because everything is intermingled.

**Comment by Error323** [comment]
@gcp that's basically what's happening now. Or I don't understand what you mean.

**Comment by gcp** [comment]
No, right now the entire PGN gets dumped to one set of chunks.

I'm saying make two sets of chunks, in different subdirs, at that point.
