### ISSUE TITLE
Support multi-game mode in client.exe

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#344]
Currently client.exe does a separate invocation of lczero.exe per game.

For tensorflow-based lc0.exe to employ batching and run efficiently, it has to run many games in parallel and communicate training data to client.exe. (and also multiple tf processes using the same GPU is not supported)

We need to decide on protocol and implement it. (I'll do that in lczero.exe but need someone to help with client.exe).

## Proposed protocol:

The lc0.exe will read commands from stdin and write responses to stdout.

(client.exe only has to support `trainingfile` and `moves` parts of `gameready`, all other commands it can just ignore or transfer to user verbatim)
### Responses:
```perl
# When game starts
gamestart <gameid> player1 <white|black>
# Info from the game to display to user
info gameid <gameid> player <1|2> side <white|black> ... (the rest as in uci info)
# bestmove (also just to display to user)
bestmove gameid <gameid> player <1|2> side <white|black> move <e2e4> ponder <e7e5>
# When game is ready and training data is generated:
gameready gameid <gameid> player1 <white|black> result <whitewon|blackwon|draw> trainingfile <filename> moves e2e4 ...
# Outputted after every game, useful for making selfplay tournaments.
tournamentstatus win <wins by player1 as white> <p1 wins as black> lose <p1 loses white> <p1 loses black> draw <draws p1 white> <draws p1 black>
```
When game is finished, lc0.exe writes training file to a disk under unique name and issues `gameready` response.

### Commands supported:
If started in `--interactive` mode, the following commands are supported

```bash
# Starts generating games
start
# Stops generating games and returns gracefully
quit
# Returns list of options
uci
# Set global option
setoption name <name> value <value>
# Set option for particular player
setoption name <name> value <value> context <player1|player2>
```
Configuration (number of playouts/network files etc) are supported both via command line flags, and uci-like `setoption` commands, not sure which of them will be more handy. Example:
```bash
# Sets for both players
setoption name Network file value abbababbbabbabb11
# Sets for player 1 only
setoption context player1 name Network file value abbababbbabbabb11
```
I'll add a list of exact options/command line flags supported later.

That's just a proposal, I'm open to suggestions of completely different way of communication between client.exe and lc0.

**Comment by ankan-ban** [comment]
A possibly simpler approach could be to have some script that launches N instances of client.exe - each of them launch N instances of lczero.exe. In the NN eval path of lczero.exe we add a mode that instead of doing the evaluation in lczero.exe, uses some sort of interprocess communication to queue the computation on a server process (running on same system). This server process is responsible only for batching up requests from different clients and running the NN eval in one go (when some fraction of N slots have been populated). With this approach, I am not sure how much we lose in inter-process communication overhead, but there are no changes needed in client.exe and relatively small/independent changes in lczero.exe (it can still remain single threaded and search the tree exactly same way it's doing today).

**Comment by mooskagh** [comment]
What do you think to be the most reasonable way to support both lc0 and lczero? Particularly, it should somehow:

-  know whether to run lczero.exe or lc0.exe
-  pass different command line parameters (sent from server) to lczero vs lc0
-  check engine's version and pass to server. should lc0 and lczero version be in sync?

Ideas are welcome.

**Comment by killerducky** [comment]
I prefer to do a clean switch to lc0.exe only. I the outstanding issues are:

* OpenCL implementation that is at least not way worse than lczero.exe. I think just porting Network and opencl from lczero.exe to lc0.exe will work for this. We can improve it with batching support later.
* client support for lczero.exe. I don't think we need to support both, just make a clean switch.
* appveyor build - I don't think this has to block a transition because IMO doing manual builds is still better than maintaining two codebases.

Since we are having some issues making progress it makes sense to have a feature freeze on lczero.exe. There are many experiements to be done that don't require code changes to lczero.exe (training hyperparams, net resets, tuning some constants like PUCT). This can double as a good time to work on the transition.
