### ISSUE TITLE
"go nodes N" broken?

### ISSUE THREAD

**Issue by killerducky** [glinscott/leela-chess#400]
Users are reporting the master branch doesn't work with `go nodes N`. I think maybe #383 changed this because one of the Limits returns either 0 or a magic -1, and then the new max code changes that to 1ms. I'm at work now so I can't verify this and a quick read of the code I'm not sure exactly what happens.

Also I made a mistake by pulling #383 into master instead of next, along with a few other PRs so master is not v0.7 anymore.

**Comment by killerducky** [comment]
Ping @jhellis3 can you take a look?

**Comment by Tilps** [comment]
get_search_time ...

    if (Limits.use_time_management() && !Limits.dynamic_controls_set()){
        return -1;
    }

    auto search_time = Limits.movetime ? Limits.movetime : Time.optimum();
    // We must ensure search time is non-negative to use time management
    search_time = std::max(1, search_time - cfg_lagbuffer_ms);
    return search_time;

and ...

    bool dynamic_controls_set() const {
        return (time[WHITE] | time[BLACK] | inc[WHITE] | inc[BLACK] | npmsec | movestogo) != 0;
    }

    bool use_time_management() const {
        return !(mate | movetime | depth | nodes | perft | infinite);
    }

There are a few confusing things here:

- go without any qualifications doesn't set any limits.  This results in dynamic_controls_set being false, but also use_time_management to be true! (what?!?).  Strangely the first if statement seems designed to catch exactly this one case, which is why reading it makes no sense...
- The previous behavior of go nodes only seems to have worked because Time.optimum() was returning 0 (no total time and no increment) and the latency was subtracted off resulting in a negative value.

What I would like to see perhaps:

new method: Limits.no_limits_set() - returns ! the full set of limits.
use_time_management() same implementation with && !no_limits_set added. (Although this is actually equivalent to the existing logic in dynamic_controls_set - so I don't see why we need both...  And get_search_time appears to be the only place which uses either... so we can probably just delete one)

Then get_search_time() implementation looking something like this.

    // Move time doesn't use time management, but it does imply a search time, so it falls through.
    if (!Limits.use_time_management() && !Limits.movetime){
        return -1;
    }

    auto search_time = Limits.movetime ? Limits.movetime : Time.optimum();
    // We must ensure search time is non-negative to use time management
    search_time = std::max(1, search_time - cfg_lagbuffer_ms);
    return search_time;

**Comment by jhellis3** [comment]
@killerducky , I agree with @Tilps here in that the code could benefit from considerable simplification.  

In addition to what Tilps highlighted above, I can also say that playouts/visits/nodes are also a bit of a mess... 

Currently, I do not feel comfortable enough with this part of the code to do a large unification/simplification without fear of unintentionally breaking something else...  I can get around to it eventually, but if someone else beats me to it that would be great :grinning: 

I did write what I believe to be a small fix & simplification addressing both the issue here and the one Tilps covered in #360 while leaving the rest of the code intact.  But please double check :).

https://github.com/jhellis3/leela-chess/commit/530b2045ce2d142f5c184a7aa858c2c7a5624556

https://ci.appveyor.com/project/jhellis3/leela-chess/build/26/job/p9elcmibgj80ta8m/artifacts
