### ISSUE TITLE
Something I've been thinking about....

### ISSUE THREAD

**Issue by hydrogenpi** [glinscott/leela-chess#431]
LeelaZeroChess is getting very popular these days. That's probably an understatement, its getting quite a lot of positive buzz, to say the least. 

To be fair, there are many people who may not know about LeelaZeroGo, since in the West Chess  has always been order of magnitude more popular than Go. Many people may not know, for example, that LeelaZeroChess owns its original existence to the LeelaZeroGo code/project, which itself was based on the AlphaZeroGo paper. Deepmind only went after Chess after it had already finished perfecting Go. 

Suffice it to say, Chess is much more easier to perfect than compared to Go. All one has to do is look at the number of self-played games per day that is pumped out comparing the lczero.org to the zero.sjeng.org projects and its obvious that Zero Chess is progressing faster. 

Recall that it took Google over 40 days of training in order to get a high level Go engine, but it took them only 4 hours to perfect Chess. 

So I'll get to the point, at this moment the Chess Zero project already has way more volunteer contributors than the Go project has. Even though Chess project started months after the Go project and was created from the original source of the Go project. 

Since Chess project will be perfected first, will the Chess community be willing to share cycles or later on switch to Go and help the Go community in terms of client compute donation of cycles?

**Comment by bastiaf** [comment]
In chess the strength graph becomes very flat, so a lot of games will be needed to train LChessZ to gain any strength, whereas LZ is already very strong. And maybe new runs will be started, trying to train larger networks from the beginning. I think it is a little bit early to see an end of the LChessZ training. And doesn't anyone wait for the day LChessZ can beat the latest Stockfish version? 😃

Additionally LChessZ self-play games need much less computation power then LZ self-play games (my PC in able to play ten times more chess than Go games). It is questionable how many of the clients which currently help in the LChessZ project can help in the LZ project. And if it is decided to train a 40x256 network then LChessZ will need a lot of resources too.

I think translating the LZ page to Chinese would already help. And I think LChessZ is more attractive, the webpage looks nicer, the zoomed in graph is motivating because it makes ELO gains more clear. There are a lot of other motivating things: user accounts, chat, Google forum, online live games against LChessZ.

**Comment by killerducky** [comment]
Everyone is free to use their own computer power however they please. I hope many of these projects are successful.
