### ISSUE TITLE
Bluescreens when self-training Leela on multiple Radeon GPUs

### ISSUE THREAD

**Issue by shellster** [glinscott/leela-chess#491]
I have a crypto mining rig running Windows 10.
The specs are: 7 Radeon RX 580 GPUs, and an 8th gen hex Core i7-8700K CPU.
I can run XMR or ETH cracking via OpenCL for days without any system instability.
I can run a single instance of client.exe on a single GPU without instability.
However, if I start spawning mulitiple instances of client.exe, one for each GPU, I quickly get a blue screen with either a TDR Timeout or a "Hung thread in driver".  This makes it impossible to donate significant compute power to the project.

**Comment by gcp** [comment]
>I quickly get a blue screen with either a TDR Timeout or a "Hung thread in driver"

Report this to AMD. They're the only ones that can fix their broken drivers.

**Comment by shellster** [comment]
The fact that this only occurs when training Leela and not doing other GPU intensive things would seem to indicate it is a problem with Leela.

**Comment by inversed-ru** [comment]
Try increasing TDR timeout or disabling TDR completely. Here is the link to the [TDR registry keys](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys). AMD GPU support is not exactly great right now. Out of curiosity, what is your performance on a single RX 580 using "go infinite" command at depth 25?

**Comment by gcp** [comment]
>would seem to indicate it is a problem with Leela.

"blue screen with either a TDR Timeout or a "Hung thread in driver"

There is not even a discussion possible that the above is a driver bug. Only driver bugs can bluescreen the machine, and it's quite literally telling you that the driver is hanging.

The fact that other things that use the GPU do not run into these bugs does not mean the bug is not in the driver. If customers do not demand that the driver gets fixed, the driver will not get fixed. It is not difficult.

>AMD GPU support is not exactly great right now.

If "AMD support were not great", the program would have relied on CUDA and cuDNN from the beginning (like literally everything else that does Machine Learning), not contain a complete re-implementation of cutting edge DCNN support with code that has been extensively tested and optimized on AMD GPUs, nor contain a tuner to support all different GPU models (not necessary with CUDA/cuDNN, NVIDIA does it all for you), and so on.

But no, the authors cannot help it that AMD's drivers still have extensive threading bugs, that AMD has "accidentally" removed OpenCL support from the latest drivers for their legacy cards, that AMD withheld fast fp16 support from the Vega OpenCL drivers, or that for some not-yet-determined reasons the Vega OpenCL drivers apparently perform much more poorly than the Fury ones.

**Comment by inversed-ru** [comment]
> There is not even a discussion possible that the above is a driver bug. Only driver bugs can bluescreen the machine, and it's quite literally telling you that the driver is hanging.

Because it sounds exactly like the TDR timeout problem, which can happen on any GPU during a compute-heavy load. Here is a [guide on changing TDR values](https://support.allegorithmic.com/documentation/display/SPDOC/GPU+drivers+crash+with+long+computations).

> ... for some not-yet-determined reasons the Vega OpenCL drivers apparently perform much more poorly than the Fury ones.

Given the fact that Vega is on the level of gtx 1080 and 1080ti in all compute benchmarks I've seen, but barely outperforms gtx 750ti in lczero, it is not unreasonable to suppose that something is not quite right with the current implementation.

**Comment by shellster** [comment]
Well disabling TDR checks fixed that issue but the thread stuck one remains.  I'm going to try training in linux and see if I can get it working.  Couldn't find anything else on the internet that helped either.
