### ISSUE TITLE
this project is fubar

### ISSUE THREAD

**Issue by hydrogenpi** [glinscott/leela-chess#596]
https://github.com/glinscott/leela-chess/issues/570

**Comment by syzygy1** [comment]
Do you expect anyone to obey your "commands and directives"? Just wondering...

**Comment by MTGOStark** [comment]
1. Was already done with ID 262. It had an immediate spike but then continued regressing. The problem precedes 253 and may be a larger issue. The reason for the regression should be found first, then reverted, or reverted for the sake of debugging. But not for strength improvements alone. 

2. Gating can be a cause of overfitting if implemented too early. The network should have robust knowledge of the gamespace before gating should be considered, otherwise it will prefer to get better along one paradigm rather than at the game as a whole. For example, in quantitative financial algorithms, if you gate for only profitable strategies (essentially +Elo), they are worse in walk-forward testing because no strategy is always profitable, and it will fail in the markets in which it didn't improve itself for. In the same way, Leela may get better at playing certain positions, but worse in others, or even in general, if gating is implemented too early. Considering there is still plenty of headroom until it reaches SF/AZ level, I don't think gating is appropriate right now. Gating now would probably see faster Elo gains in the short term, but create a lower ceiling in the long term. Leela still blunders simple tactics, and doesn't understand certain positions, indicating she does not have robust knowledge of the gamespace yet. 

3. We will if it comes to it. For some reason developers seem lax on giving chess the NN treatment or releasing chess weights. It also didn't take long for the Leela Go guys to implement ELF weights. 

4, 5. See 2.

6, 7. I agree we could be doing more community outreach and encouragement. Maybe some more exhibition matches, facing recent, strongest nets but at only 1 or 10 nodes per move.

**Comment by killerducky** [comment]
dup of #570
