### ISSUE TITLE
Improve the self-play Elo graph

### ISSUE THREAD

**Issue by killerducky** [glinscott/leela-chess#623]
The lczero.org Elo graph is not as accurate as it could be. Everyone agrees it would be nice if Someone would do the work to improve it. A nice first step would be to use Ordo and include all matches, not just the previous vs next matches. Chad from discord wrote a one-off script to do this, and to my eyes the dip and then recovery of Elo seems to match external engine Elo tests better:

![Improved Self-Play Elo](https://media.discordapp.net/attachments/425419483016855563/447080015515877416/unknown.png)

So Someone could write some golang code to take the existing match data and run it through Ordo. We could occasionally do manual schedules of current nets vs one or more past nets to reduce the accumulated Elo error from doing sequential tests only like we do now.

Edit: Also every extra net we test against means ~400 clients are going to download an extra 80MB net, for the sake of drawing a prettier line. So I think we should keep these extra matches to a minimum, because I think the value of a prettier line is not that high.

**Comment by luigio** [comment]
What is Ordo?

**Comment by killerducky** [comment]
Ordo is a ratings calculator

https://github.com/michiguel/Ordo

**Comment by cn4750** [comment]
I used the following command to generate that graph using Ordo:
`ordo-win64.exe -Q -J -N 0 -D -a 3033 -A "15" -W -n6 -s500 -V -U "0,1,2,3,4,5,6,7,8,9,10,13" -j stats.txt -p games.pgn`
I keep a pastebin of the output [here](https://pastebin.com/i1cqjeZ7).

My suggestion for regression testing is simply to run one every 10 (or so) tested nets. Simply test the current best net against the best net 10 nets ago. This will help keep things linked tighter.

**Comment by TCECfan** [comment]
Here's a thought:  Do we need the self-play elo matches at all?  Do they serve any purpose?  I doubt it.
No-one really trusts the self-play elo, and why should anyone whilst we have a glut of (superior) external elo tests, lists and sheets.  Our gating at EloDelta -150 is so low that most of us have forgotten that we are gating at all.
We could generate at least 2% more self-play training games if we ran these instead of self-play elo match games.

**Comment by trophymursky** [comment]
Another thing that I think is important is that error bars should be added to at least the self play delta. Instead of using the expected value for the result of a game (points /number of games) in the ELO formula you use the expected value +- 1.96*standard deviation of the mean distribution (calulated by standard deviation of the distribution /square root of the number of games) for the Elo calculation.

**Comment by killerducky** [comment]
Self play has used Ordo for a long time now I think.
